"""empty message

Revision ID: eb464694915a
Revises: c61ea666e921
Create Date: 2024-11-28 16:56:44.808643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb464694915a'
down_revision: Union[str, None] = 'c61ea666e921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('cities', sa.Column('region', sa.String(length=100), nullable=False))
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cities', 'longitude')
    op.drop_column('cities', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cities', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('cities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cities', 'region')
    op.drop_column('cities', 'population')
    # ### end Alembic commands ###
